### ISSUE TITLE
Nothing happens on clicking Give feadback

### ISSUE THREAD

**Issue by altteo** [gitspeak/community#12]
![image.png](https://cdn.filestackcontent.com/mmsdAI3NRemt3ApRnla8)

**Comment by somebee** [comment]
It's pretty unintuitive right now. Tapping "Give feedback" simply selects the community repository. If you're already showing the community repo, nothing will happen. We ought to:

1. Hide the link when showing community repo
2. When tapping it, show a tooltip at the top indicating that the community repo was now selected, and that you can add issues etc etc.

**Comment by altteo** [comment]
Maybe leave only my communities in the list and separate gitspeak community? (just a proposal not sure that it is a good one)
