### ISSUE TITLE
My own repositories not available

### ISSUE THREAD

**Issue by altteo** [gitspeak/community#16]
![image.png](https://cdn.filestackcontent.com/RjSlmncUTjyxrP7YXHPN)

**Comment by perborgen** [comment]
Which organisations did you install it on at Step 2?

**Comment by altteo** [comment]
Don’t remember. How I could see that? And connecting repos and organizations is pretty common tasks, they should not be only on startup. For example if I work with gitspeak and then join another organization I will not understand how to add it to gitspeak.

**Comment by perborgen** [comment]
It is possible to add new repo's in the general interface as well, but it's a bit hidden. Click on the name of your repo (top right corner) and then choose "Add repositories".



Would it help if that option also appear if you click on your profile pic in the bottom right corner?

**Comment by altteo** [comment]
Ok, i've understood how it works. Now I see mine repos. So it is not a bug, but not clear UX.

The thing is that same full page access settings that are used on first application init also are used letter. That made me think that i'm doing some critical stuff. 

I propose to make settings for connected companies and repos in the popup.

The adding of companies and repos are at theirs's place now (there is no need to put it in the profile). Maybe you can put it not in the hidden dropdown, but add some icon to the right. 

After a little thinking it appears that we still think in a "webish" way. Companies connections and available repos should be accessed through main menu. The best way is to put settings in the "Settings" menu and there "Companies and repositaries". Maybe you should also put profile there as another submenu.

**Comment by Pistus** [comment]
The workspace situation and syncing has been improved a lot, so I´ll close this. We still need to work on the onboarding of new users which is an open issue.
