### ISSUE TITLE
Improve linking of repo to local repository

### ISSUE THREAD

**Issue by aalemayhu** [gitspeak/community#19]
I forgot to link a project and was scratching my head over why the contextual pasting was not working. Just thinking out loud, maybe the user should get a modal encouraging them to link to a local repository early? Would have been nice to see it shortly after opening the project up for the first time.

Very cool project, thanks!

**Comment by perborgen** [comment]
Yes, that's a very good point, we'll look into how to encourage that!

**Comment by aalemayhu** [comment]
This is working much better now that you get question `Is this code in your repository[...]` and the  modal for linking shows up when hitting yes. Great work 🌮

![Screenshot 2019-08-02 at 9 01 28 PM](https://user-images.githubusercontent.com/925044/62392906-00bb9e00-b569-11e9-9eba-f4b7b0055d68.png)
![Screenshot 2019-08-02 at 9 01 34 PM](https://user-images.githubusercontent.com/925044/62392918-07e2ac00-b569-11e9-95fd-b4001592c7e5.png)
