### ISSUE TITLE
Issue header cleanup

### ISSUE THREAD

**Issue by altteo** [gitspeak/community#20]
Maybe you should hide empty parameters of the issue? If you use it as interective interface (for exxample to set milestone) it is better to add some actions menu to the issue. The majority of views will be just reading the header of the issue. So let's clear up inteface a little and leave only the things that matter. And maybe parameters should be put in one line - to take minimal vertical space.

![image.png](https://cdn.filestackcontent.com/Wlv7g5N5R4W7CnMZtRYT)

**Comment by perborgen** [comment]
We need some kind of ability to set these parameters though. If they are completely hidden when empty, people won't know how to e.g. add a label to an issue.

**Comment by altteo** [comment]
<img src="https://cdn.filestackcontent.com/ZurbwqdTWCw1mTyRlwfY" width="329" title="image.png">

**Comment by altteo** [comment]
Something like this (just a concept). You could put any actions in dropdown in three dots icon... Frankly I want an issue thread look more like telegram conversation.

**Comment by perborgen** [comment]
Thanks for sketching out your thoughts! Here's how it would look with horisontal list instead of vertical. It does make room for extra space at least.

<img src="https://cdn.filestackcontent.com/3X1oDWksREyepV3iHQQ5" width="825" title="Screenshot 2019-02-28 at 08.03.59.png">

**Comment by altteo** [comment]
For me it looks much better in horizontal flow.

**Comment by somebee** [comment]
I've tried a lot back and forth, and agree that it often looks better in horizontal, but when you start adding labels and assigned users etc, (or the user has a small screen) it will need to wrap. And when it wraps it looks pretty bad. We should explore some alternatives; I do agree that we need to partly hide unset properties. Some suggestions for at least improving it:

* Hide milestone-prop alltogether if project has no milestones
* Keep submitted by and assigned to on the same line. They are relevant.
* Any unset properties are only shown as icons on the far right of top line.

**Comment by altteo** [comment]
Don't be universal (like "here we will have a place for all parameters"). Be more specific. For example author's avatar in my opinion should be to the left of the issue name (in the header and also in the list).

You already have a label (draft, open...) after the name of the issue (and here you have wrap case by default), why not to put all other labels there - just all labels in one place after the name.

Now we have left only assignee and milestone. You could just put some text in the second line (like subtopic): _opened **2 days** ago, assigned to **somebee**, version **1.6.0.**_

**Comment by altteo** [comment]
By the way this approach will allow you to represent issue almost the same way in the list and individually.
And also not sure that the numeric ID of the issue is valuable information.

**Comment by altteo** [comment]
If there could be several assingnees (maybe better call them participants?) then the second string could have for example a row of avatars on the left and milestone on the right (in small resolutions it will just become two lines)

**Comment by Pistus** [comment]
This has been reworked a lot since March - check it out now and see if you like it:)
