### ISSUE TITLE
Does pasting menu bothers only me?

### ISSUE THREAD

**Issue by altteo** [gitspeak/community#21]
I mean maybe I would need sometimes additional pasting options, but in majority of cases I just want to paste (in the format that all surraunding text is or just a picture without thinking about it's resolution). So additional step during pasting makes it more complicated. Maybe you could put such options in the right-click context menu. And when hot keys are used just paste the content in (some opinioted way).

![image.png](https://cdn.filestackcontent.com/muBEAq23RnahS4KLX4nf)

**Comment by perborgen** [comment]
I agree that this should be omitted when pasting images. In that scenario, we should rather highlight the ability to toggle high-res on and off later on.



As for the "contextual code snippets", I'm not sure. What are your thoughts on that area? Btw, if you're not aware what contextual code snippets are, you can check out this video (from 0:40):

[https://www.youtube.com/watch?v=iSyb0S6W4sM](https://www.youtube.com/watch?v=iSyb0S6W4sM)

**Comment by altteo** [comment]
I think you should make pasting with CTRL+V or SHIFT+Insert without any additional questions. And also add context menu on right-click for different options for manual choosing.

**Comment by somebee** [comment]
Yeah. For images we should definitely turn off the choice during paste. As for other types of pasting, we should be smarter about it, and probably go for the most obvious option, and then rather showing the menu after past is finished, and if you choose another option we revert the paste and redo it in the chosen formatting.

**Comment by somebee** [comment]
Removed menu for images now

**Comment by Pistus** [comment]
Image handling has been improved a lot in general with no annoying menu, async uploads that allows you to continue work without waiting for upload, etc.
