### ISSUE TITLE
Clicking the tag in the issues list sets the filter

### ISSUE THREAD

**Issue by altteo** [gitspeak/community#23]
At some point (when i clicked an issue) a lot of issues disapears.

<img src="https://cdn.filestackcontent.com/FzDmXdGAR3GkSCmxFWS2" width="679.5" title="image.png">

**Comment by altteo** [comment]
Restarting an app resolves the problem.

**Comment by altteo** [comment]
I figured out what happened. I clicked the issue in the list and hit a tag - that have set a filter. Though i just wanted to activate the issue it filled like a bug (but it's not).

**Comment by perborgen** [comment]
That's actually intended behaviour, that an issue is applied when you click on it. To "reset" so that you see all issues again you can click on the label option above all the issues, and then choose **Clear filter**.



I guess we should explain this behaviour better and make it more apparent.

**Comment by altteo** [comment]
It is not very convinient. When I click some issue to activate it and by chance hit a tag not desired things (and not obvious) happen. My proposal is to set filter on tag on double-click or ctrl-click.

**Comment by somebee** [comment]
I agree. Removed the feature for now. Will make it so that cmd/ctrl+click will activate it as filter. Thanks for all the valuable feedback :)
