### ISSUE TITLE
Repos in extra sidebar visible all the time

### ISSUE THREAD

**Issue by silvio-e** [gitspeak/community#25]
Because we have a lot of repos we work daily in it would be great to have the repos in an extra sidebar, because having them all hidden in the dropdown makes it hard to get a feeling for the list and switching between them taking to much time.

**Comment by perborgen** [comment]
I see. How about if you were scoped into organization level, so that you'd have issues and PRs from all repo's in the same view? Would that solve the problem?

**Comment by silvio-e** [comment]
Not sure. Perhaps. Would have to see a sketch :) But another idea from one of my devs was to have perhaps a list with accordions. Clicking on a repo would reveal the list we have now too in every repo.

**Comment by perborgen** [comment]
We've now deployed support for organization view. Meaning you can see Issues/PRs/Casts for all repo's on an organization in the same view. This should make it easier for those who're working on multiple repo's. Does it help @silvio-e?

**Comment by silvio-e** [comment]
Definitely! That's a great one! :)

**Comment by silvio-e** [comment]
Reduces the need have to have a list in the sidebar.

**Comment by perborgen** [comment]
Great to hear that! :)

**Comment by perborgen** [comment]
This one has been improved even more @silvio-e , as you can decide for yourself which repos you want to appear in the dropdown menu (by making them active/inactive in the Settings menu). Also, we're only displaying the repos from the organization you're currently at, which makes it a lot cleaner.

**Comment by Pistus** [comment]
I´ll close this as you can select the repos you want to show in the sidebar.
