### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by silvio-e** [gitspeak/community#26]
I see that notifications would be really important. I wouldn't have known that you answered to my feedback if I hadn't accidentally checked my emails, where I notified about repo activities. But that is definitely not the best place :D

**Comment by perborgen** [comment]
Yup, it's on our list :)

**Comment by silvio-e** [comment]
Topp!! :)

**Comment by perborgen** [comment]
Hey @silvio-e ! We've added basic support for Notifications now. It's actually made the collaboration work much smoother internally in GitSpeak, as we've actually started replying to each others' Issues and comments. Previously, it just drowned in all the GitHub fuzz. 



Would love to hear you feedback on this one. It can surely be improved, but it works pretty well already :)
