### ISSUE TITLE
How to add a repo that is NOT mine, but I am listed as a collaborator?

### ISSUE THREAD

**Issue by nemanjaglumac** [gitspeak/community#28]
I couldn't find a way to add a repo that was created by my friend. I am listed as one of the collaborators and we both contribute to that same code base. 

If I fork it, everything works fine, but many times a few people simply work on the same repo (different branches) without forking.

Is there a way to add such repository to GitSpeak?

Following this link, one can see all the repos in their GitHub account (including the ones owned by others):
[https://github.com/settings/repositories](https://github.com/settings/repositories)

**Comment by perborgen** [comment]
Hey! Before you can add a repo, the GitSpeak app needs to be installed on the organisation/user which owns the repo. You likely don't have admin access to the org which owns the repo. So either you'll need to get that, or you'll need to ask your friend to install GitSpeak on the owner.

**Comment by nemanjaglumac** [comment]
Thanks for quick response. 
Much apreciated.

**Comment by perborgen** [comment]
@nemanjagulmac when you click on "Install more", and are navigate to GitHub, this organization is listed on their page along with a "Request" option, right?

**Comment by nemanjaglumac** [comment]
@perborgen : organization - YES. 
Friends and their repos - NO :)
