### ISSUE TITLE
As a user, I would like to have the option to cancel adding new repo/organization and go back to the app.

### ISSUE THREAD

**Issue by nemanjaglumac** [gitspeak/community#29]
# The issue

Right now, there is no option to cancel if you've clicked "add new repo/organization" by mistake. The only option you have is to click `finish`. 
This can be confusing to many new users.

Also, when you want to close that window, the whole app minimizes. When you open it again, you're still in the "adding new repo phase".

## How to reproduce

Follow the gif screenshots provided below.

1. Add new repo
[https://cl.ly/f7c0d9](https://cl.ly/f7c0d9)

2. Add new organization
[https://cl.ly/14fc79](https://cl.ly/14fc79)

**Comment by perborgen** [comment]
Thanks a lot for the isse and the videos, would it be sufficient with a "Cancel" option at the bottom of the page?

**Comment by nemanjaglumac** [comment]
Yeah. "cancel" or "nevermind" or anything similar. 

If it's not too much work, maybe even add "esc" key support.

**Comment by perborgen** [comment]
Got it!

**Comment by perborgen** [comment]
We just deployed a "Cancel" button, @nemanjaglumac !
