### ISSUE TITLE
Discarding EMPTY issue breaks the app

### ISSUE THREAD

**Issue by nemanjaglumac** [gitspeak/community#30]
# The Issue

When you try to discard the **empty** issue draft, it doesn't work and what's more - it breaks the whole app. 

_Note: I wasn't able to reproduce this for the issues that were not empty to begin with!_

## How to reproduce?

1. create new issue
2. without typing anything, try to discard that empty draft
3. try clicking anywhere within the app (it will not work)

The only solution after this is to completely close the app and restart it again.

Check out the provided gif screenshots below:

* [Single empty issue](https://gitspeak.com/gitspeak/community/[https://cl.ly/b69f04](https://cl.ly/b69f04))
* [Multiple empty issues](https://gitspeak.com/gitspeak/community/[https://cl.ly/61d0a6](https://cl.ly/61d0a6))

EDIT: Discard **ONLY** works as it should when **both** title and body are populated. In every other scenario, it will break the app. 

[](https://cl.ly/b69f04)

**Comment by nemanjaglumac** [comment]
Here you can see the desired behaviour when all fields are populated:


- [Single populated issue](https://cl.ly/3555f9)

- [Multiple populated issues](https://cl.ly/056531)

**Comment by perborgen** [comment]
Thanks for reporting this one!

**Comment by somebee** [comment]
Should be fixed now
