### ISSUE TITLE
Deleting the issue on GiHub doesn't delete it in the app

### ISSUE THREAD

**Issue by nemanjaglumac** [gitspeak/community#31]
# The Issue

When you delete the issue on GitHub, it doesn't reflect (update) it in the app. 

## How to reproduce?

1. Create new issue in GitSpeak (optional) or select the existing issue
2. Open in in the browser (GitHub)
3. Delete the issue from GitHub page
4. Go back to GitSpeak and observe that the deleted issue is still there and you can even edit it, close it, reopen it, etc.

Check out provided gif screenshot below:

[https://cl.ly/2d42c8](https://cl.ly/2d42c8)

## Additional notes

- It would be really helpful if you can provide a delete button within the app (with some warning, of course)

**Comment by somebee** [comment]
We'll implement this. Thanks for reporting :)

**Comment by somebee** [comment]
Should work now
