### ISSUE TITLE
Sync GitHub Boards with GitsSpeak Boards

### ISSUE THREAD

**Issue by mvpopuk** [gitspeak/community#33]
Is it possible to have same boards position in GitSpeak as it is in GitHub ? For instance if I have a task under the "Doing" board, in GitSpeak the "Doing" board is empty. Somehow will be awesome if GitSpeak will know boards position.

**Comment by perborgen** [comment]
This feature is on its way @mvpopuk ! It'll hopefully be in place sometime next week.

**Comment by mvpopuk** [comment]
Awesome, thanks.

**Comment by perborgen** [comment]
We're a bit behind schedule on this one, but we're aiming for this week :)

**Comment by mvpopuk** [comment]
Looking forward to it 👍

**Comment by somebee** [comment]
Early version of this deployed now :)
