### ISSUE TITLE
Issue acitivity view

### ISSUE THREAD

**Issue by plapnt87** [gitspeak/community#40]
Hi There, I only can see part of my activity in GitHub. (From last year). 

I'm doing something wrong?

**Comment by plapnt87** [comment]
Also, there is the possibility to remove the repositories that I have added? 

By mistake I have added few that I don't care much. Thanks!

**Comment by perborgen** [comment]
Hey @plapnt87 , right now it's not possible to deactivate repos, but I've created an Issue about that internally, so it's on our list.

Regarding seeing only parts of your activity, it could be that it hasn't fully synced yet. Can you try to refresh (cmd+r)?

**Comment by plapnt87** [comment]
Hey @perborgen, thanks for your fast reply. Regarding the second issue I think I uderstood why. Basically in our team we don't use github (website) to create pull request or merge, but is our CTO that doeas this via command line. Can be this the cause?

**Comment by perborgen** [comment]
Ah, I see. Is your CTO using the [hub](https://hub.github.com/) command from GitHub? Or just using the `git` command? 




As far as I know it's only via the former that the PR is also created on GitHub. And if it's not on GitHub we don't see it, at least not today. But I assume we could find it locally..

**Comment by plapnt87** [comment]
Yep, he only use git command. Thanks for your help. I will try to use is locally and see how it goes. Anyway I love the concept. Really cool!

**Comment by perborgen** [comment]
Gothca! Btw, feel free to join[ our Slack chat](https://join.slack.com/t/gitspeak/shared_invite/enQtNDE4MzY0NDY3NzkyLWFhMzg1YzQ4ZWIwOGMyYzhiZTYxMmEyZTAzMTE5ZTBmMzE4ZDA5ZjM1N2ZjMDZjMmE5M2M4ZDNkN2JjNGM2YzQ). That way you can reach out whenever you have a question:

**Comment by plapnt87** [comment]
Thanks I have joined the group
