### ISSUE TITLE
Discarding creation of new issue causes errornous behaviour

### ISSUE THREAD

**Issue by michaelo** [gitspeak/community#41]
Steps to recreate:

1. Go to "Issues"
2. Press "New"
3. Press "Discard"
4. Confirm the dialog that pops up

Observation:

* Draft issue is still there
* Not able to navigate anywhere in application (can't look at other issues or change to e.g. "Notes" etc.)

Tested on macOS

![image.png](https://cdn.filestackcontent.com/TC6gQpO7RT2vsKFC05gJ)

**Comment by perborgen** [comment]
Thanks for the report @michaelo ! We'll make sure that this is fixed next time we deploy, which should be this week.

**Comment by somebee** [comment]
Fixed :)
