### ISSUE TITLE
No image if saving issue while uploading

### ISSUE THREAD

**Issue by Pistus** [gitspeak/community#43]
Since I am very very fast at making issues I managed to add an image and save it before the uploader finished. The result is not pretty as the image is broken on Github - but shows in my gitspeak. Which is confusing for other people:)

![Screenshot 2019-03-21 at 16 21 43](https://user-images.githubusercontent.com/1829960/54762997-7a27a500-4bf5-11e9-8cea-adb4aabd5172.png)

A solution would be to disable the create / comment buttons while uploads are happening.

**Comment by perborgen** [comment]
Ah, thanks a lot for this one, we'll fix it :)

**Comment by aalemayhu** [comment]
@Pistus Just tested it and this issue not reproducible in latest GitSpeak. Are you able to reproduce?

**Comment by Pistus** [comment]
No, this has now been fixed. 🛠
