### ISSUE TITLE
Scrollable repo list

### ISSUE THREAD

**Issue by Pistus** [gitspeak/community#44]
At the moment I have all my repos added to gitspeak, and it is more than what fits in one page of the dropdown. There is no scroll or pagination so I am unable to get to the last repos in the list. Can be reproduced by making the height of the window small.

Because of #42 I am unable to get to all my used repos:)

![Screenshot 2019-03-25 at 12 02 13](https://user-images.githubusercontent.com/1829960/54914704-dcceb880-4ef5-11e9-8410-b447c4d8b2d5.png)

**Comment by perborgen** [comment]
Thanks, this will be added on the next deployment, hopefully this week :)

**Comment by perborgen** [comment]
This menu is scrollable now, @Pistus , so I'm closing this issue.
