### ISSUE TITLE
Add projects to issues

### ISSUE THREAD

**Issue by Pistus** [gitspeak/community#46]
We use projects for both repos and the organisation. Would be nice to be able to add an issue to a project from the gitspeak issue interface. The projects list should include repo and organisation projects.

From github:
![Screenshot 2019-03-25 at 17 39 27](https://user-images.githubusercontent.com/1829960/54937737-44502c80-4f25-11e9-8974-be80f8e69eed.png)

**Comment by perborgen** [comment]
Yes, very good point, it'll be added! Will let you know when it's done.

**Comment by Pistus** [comment]
Projects is no longer supported
