### ISSUE TITLE
Support using ticks for editing issue text

### ISSUE THREAD

**Issue by Pistus** [gitspeak/community#47]
It seems I prefer to write the styling of my issues rather than using the mouse based editor. I sorely miss using ticks for inline \` and block \`\`\` text.

**Comment by somebee** [comment]
I see. You can still mark the text and press `cmd+e` for code. And for code you just write '/code' etc. (Type / to bring up the actions menu).

**Comment by somebee** [comment]
It is just not really explained yet, but I never use the mouse when writing issues / notes. Everything has shortcuts. Still, we'll add backtick for code at some point :)

**Comment by kigiri** [comment]
ctrl+e not working on linux.

**Comment by Pistus** [comment]
This is now fully supported
