### ISSUE TITLE
Markdown display issue

### ISSUE THREAD

**Issue by taw** [gitspeak/community#56]
It's not the same as github's. [For this issue](https://github.com/taw/hoi4/issues/1)

Expected (same as on github):
<img width="358" alt="Screenshot 2019-06-22 at 07 03 03" src="https://user-images.githubusercontent.com/17444/59960157-d7b0e380-94bb-11e9-8683-7c20509b11ef.png">

Actual in GitSpeak app:
<img width="434" alt="Screenshot 2019-06-22 at 07 02 51" src="https://user-images.githubusercontent.com/17444/59960156-d7b0e380-94bb-11e9-84f3-b07aad629320.png">

That's about `#` in lists being interpreted as header.

**Comment by somebee** [comment]
Thanks for reporting. Added an internal issue for this and will include fix in next release!
