### ISSUE TITLE
New repos not syncing

### ISSUE THREAD

**Issue by meleantonio** [gitspeak/community#59]
I have created new repos but it looks like they are not synced, not even in the list of repos. Also, the app seems stuck in syncing with Github.

**Comment by aalemayhu** [comment]
You can manage the repository access on this page (click configure on GitSpeak) https://github.com/settings/installations/

Don't know if this is related to your issue but I keep forgetting to give GitSpeak access to newly created repositories. IIRC GitSpeak does not support reading all repositories, you have to manually select the ones it should use.

**Comment by meleantonio** [comment]
thanks @scanf  but that's not it.

**Comment by somebee** [comment]
I'm sorry. Will look into this tomorrow morning. We're still very much in beta :)

**Comment by meleantonio** [comment]
@somebee any update on this issue? I keep having it. The app is stuck in syncing forever. This happens only with my personal account, but not with my organizations.

**Comment by somebee** [comment]
Does it work now? Our syncer freaks out when there is a repo with the same name as a previously deleted repo.

**Comment by meleantonio** [comment]
@somebee yes it does work now, many thanks for your help, I'll keep this in mind.
