### ISSUE TITLE
GitSpeak crashes on Windows when using the menu buttons

### ISSUE THREAD

**Issue by yaseralnajjar** [gitspeak/community#6]
Whenever I use the buttons on the menu above (edit view... etc), GitSpeak crashes

![image.png](https://cdn.filestackcontent.com/XNrFevTARgiEhJwkJiAx)

**Comment by perborgen** [comment]
Thanks for reporting this one, we'll look into it.

**Comment by altteo** [comment]
Confirm this.

**Comment by perborgen** [comment]
We just deployed an update which solves this. It will be downloaded in the background and you'll be prompted to relaunch the app.



It was actually an Electron bug which they fixed in their latest release.
