### ISSUE TITLE
Shortcut for new not working when inside a issue or note

### ISSUE THREAD

**Issue by aalemayhu** [gitspeak/community#60]
When editing a note I tried to hit `CMD+N` on macOS in order to create a new note so I could split the note into more relevant topics. I was expecting command new to show the compose menu but nothing happened. 

To create a new note when the cursor is inside a input field requires two steps
1) Focus on the list of issues / notes
2) Then press `CMD+N`

 or using the mouse to click the plus button. 

It would be more efficient if `CMD+N` worked regardless of where you had focused or the cursor is located.

**Comment by somebee** [comment]
Related to gitspeak/gitspeak#801

**Comment by somebee** [comment]
Fixed and deployed :)
