### ISSUE TITLE
Closing tick mark does not work as expected

### ISSUE THREAD

**Issue by aalemayhu** [gitspeak/community#61]
When starting and closing a word / sentence with tick mark, GitSpeak continues rendering the next characters as as part of the tick \`. The expected behaviour was to only render the part between the tick marks from start to finish. Not sure if this makes sense but below is a gif example of the bug

![ezgif-5-c7f31a099aff](https://user-images.githubusercontent.com/925044/62294616-a688e300-b46b-11e9-80d2-df3f0d08dea3.gif)

As you can see from the gif the code is rendered this way

`here is a snippet of code on a single line I just closed it but the line i still being presented as code?`

but I was expecting this

`here is a snippet of code on a single line` I just closed it but the line i still being presented as code?

**Comment by somebee** [comment]
Oh, that is not expected behaviour. Will look into it :)

**Comment by aalemayhu** [comment]
The work around I have found for this is to hit the right arrow key once. That seems to move the cursor out of the context it was in.
