### ISSUE TITLE
can't write description before writing the title on draft issues and notes

### ISSUE THREAD

**Issue by aalemayhu** [gitspeak/community#66]
When composing a new note and selecting the description area, GitSpeak changes the detail view to the next item on the list. Hence making it impossible to draft a issue or note without first entering the title. I was expecting GitSpeak to allow me to edit the description before entering the title. This is just a workflow thing.

Below is a gif demonstrating the bug
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/925044/62390497-bfc08b00-b562-11e9-984c-0d5dbb52b74f.gif)

**Comment by Pistus** [comment]
Yeah, this has annoyed me as well.

**Comment by aalemayhu** [comment]
This has been fixed in the latest release.
