### ISSUE TITLE
Windows 10 shows caution on starting install

### ISSUE THREAD

**Issue by altteo** [gitspeak/community#7]
Not the common caution. But like it has done a great job preventing the start of some malware.
![image](https://user-images.githubusercontent.com/1933862/53420424-d596b680-39ec-11e9-9dab-b2f2c570037e.png)

**Comment by perborgen** [comment]
Yes, this one will appear until we have enough downloads for Windows to screen it as a recognized app (even though our app has been signed with a certificate bought from a verified third party certificate issuer). Kind of annyoing, hehe.
