### ISSUE TITLE
Text jumping when hitting SHIFT+TAB

### ISSUE THREAD

**Issue by aalemayhu** [gitspeak/community#71]
When hitting `SHIFT+TAB` on the top level check item the item and it's sub item jump to the bottom left corner. I am not sure if this is a feature but I was expecting the check item to be removed.

Below is a gif demonstrating it
![ezgif-5-2ed9f3a47cef](https://user-images.githubusercontent.com/925044/62561237-ff4ae800-b87e-11e9-9cb3-8607495ef8a3.gif)

**Comment by somebee** [comment]
Fixed in dev - will deploy today or tomorrow!

**Comment by aalemayhu** [comment]
Great! Let me know if you want me to verify it.
