### ISSUE TITLE
Could not add the second issue in a row

### ISSUE THREAD

**Issue by altteo** [gitspeak/community#9]
Header and description inputs are disabled.

**Comment by somebee** [comment]
Could you describe the order? Tapping "new" twice, or first creating an issue, writing its title and description, and then tapping new again?

**Comment by altteo** [comment]
Tap new, fill in title and description, save. Issue appears. Then tap new again to fill another issue, but could not fill title and description (cursor is not blinking and typing does nothing)

**Comment by somebee** [comment]
@perborgen Could you test this on Windows?

**Comment by Pistus** [comment]
We are not prioritizing windows at the moment so will close this issue.
